name: Build Android APK

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Buildozer and dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer
        sudo apt-get update
        sudo apt-get install -y \
            git \
            zip \
            unzip \
            openjdk-11-jdk \
            python3-pip \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libtinfo5 \
            cmake \
            libffi-dev \
            libssl-dev \
            libusb-1.0-0 \
            libgl1-mesa-dev

    - name: Build APK with Buildozer
      run: |
        buildozer -v android release
      env:
        P4A_RELEASE_KEYSTORE: ${{ secrets.P4A_RELEASE_KEYSTORE }}
        P4A_RELEASE_KEYSTORE_PASSWD: ${{ secrets.P4A_RELEASE_KEYSTORE_PASSWD }}
        P4A_RELEASE_KEYALIAS_PASSWD: ${{ secrets.P4A_RELEASE_KEYALIAS_PASSWD }}
        P4A_RELEASE_KEYALIAS: ${{ secrets.P4A_RELEASE_KEYALIAS }}

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: central-jati-cell-apk
        path: bin/*.apk
