name: Build Android APK with Buildozer Action

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build with Buildozer
      uses: ArturSkowronski/action-buildozer@v1.0.3
      with:
        buildozer_version: latest
        platform: android
        buildozer_command: release
      env:
        P4A_RELEASE_KEYSTORE: ${{ secrets.P4A_RELEASE_KEYSTORE }}
        P4A_RELEASE_KEYSTORE_PASSWD: ${{ secrets.P4A_RELEASE_KEYSTORE_PASSWD }}
        P4A_RELEASE_KEYALIAS_PASSWD: ${{ secrets.P4A_RELEASE_KEYALIAS_PASSWD }}
        P4A_RELEASE_KEYALIAS: ${{ secrets.P4A_RELEASE_KEYALIAS }}

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: central-jati-cell-apk
        path: bin/*.apk
