name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: beevelop/kivy:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build APK with Buildozer
      run: |
        apt-get update && apt-get install -y openjdk-11-jdk
        pip install buildozer
        buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: central-jati-cell-apk
        path: bin/*.apk
