name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Buildozer and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git zip unzip openjdk-11-jdk python3-pip \
          autoconf libtool pkg-config zlib1g-dev \
          libncurses5 libncursesw5 libffi-dev libssl-dev \
          cmake wget
        pip install --upgrade pip
        pip install cython buildozer

    - name: Install Android SDK command-line tools
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O sdk-tools.zip
        unzip sdk-tools.zip -d latest
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV

    - name: Accept Android licenses & install tools
      run: |
        sdkmanager --sdk_root=$HOME/android-sdk --licenses <<< "y"
        sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-34" "build-tools;34.0.0"

    - name: Build APK with Buildozer
      run: |
        buildozer android debug
        ls -la bin/

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: central-jati-cell-apk
        path: bin/*.apk
